Add data pull for testing
choderalab/asapdiscovery pull request #225
Opened 2023-04-14 06:52 UTC by hmacdope

Fixes #187. 

Adds infrastructure to pull down files for testing from a public AWS S3 bucket.

2023-04-14 09:01 UTC, JenkeScheen requested changes
LGTM but could you remind me

2023-04-14 15:11 UTC, apayne97 commented
it's hard to overstate my delight in making tests that test the testing capabilities

2023-04-14 15:45 UTC, apayne97 reviewed
I'm not familiar with hardly any of these tools yet, so I just have general questions for right now as I think "out loud" about this. 

- [x] If I wanted to add descriptions to the files in S3 (lets say the Mpro_combined_labeled.sdf), where should I do that? in a script that specifically downloads that file? in the yaml file? in the S3 bucket?
- [x] does it make sense to have scripts that download all of a subset of files that might be generally useful? like something that downloads all the relevant examples for a specific module? or maybe 1 per example?
- [x] what overlap between files that are more like tutorial usage examples and files that are for tests should there? answering my own question here, maybe we could have files that are primarily examples and then the internal testing function can just know to pull them from there.

- [ ] should the `testing` directory have an `__init__.py`?
- [ ] how would I write a script that pulls a specific file without having to re-cache? Maybe you can answer this by just making examples in #223 once this PR is pulled

2023-04-14 20:30 UTC, kaminow requested changes
minor suggestion, but looks good!

2023-04-14 20:30 UTC, kaminow commented on asapdiscovery-data/asapdiscovery/data/testing/test_resources.py
> +        test_files = yaml.safe_load(f)
check that `test_files` exists first?

2023-04-16 22:57 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/testing/test_resources.py
> +    except Exception as e:
There are quite a few in pooch, but the `from e` on L90 should chain them together nicely so that you get a full trace.

2023-04-16 22:58 UTC, hmacdope commented
> LGTM - remind me what happens when the file is already downloaded?

If the file is already downloaded you will just get the path to the existing file returned. :)

2023-04-16 23:19 UTC, hmacdope commented
@apayne97 I'll answer each question. 

- [X] If I wanted to add descriptions to the files in S3 (lets say the Mpro_combined_labeled.sdf), where should I do that? in a script that specifically downloads that file? in the yaml file? in the S3 bucket?

> I would say the best place to add a short description is the YAML bucket as a comment, I think tacking on explicit metadata will become a bit unwieldy. 

- [X] does it make sense to have scripts that download all of a subset of files that might be generally useful? like something that downloads all the relevant examples for a specific module? or maybe 1 per example?

 > For testing at least, each individual module that needs testing can decide this and setup a fixture to do that once and once only, eg in `conftest.py` for you module you can do 

```python
@pytest.fixture(scope='module')
def my_important_files():
    a = fetch_test_files("a")
    b = fetch_test_files("b")
    c = fetch_test_files("c")
    return a, b, c
```

> This is also how you avoid hitting the cache too much as this is only called once per pytest session.

> Pooch also handles all the behind the scenes caching, and we don't do any explicit cleanup, so if you already have the file downloaded you wont have to download it again in the next pytest session. Hopefully that answers your question. I'll put some examples together in #222. 

- [X] what overlap between files that are more like tutorial usage examples and files that are for tests should there? answering my own question here, maybe we could have files that are primarily examples and then the internal testing function can just know to pull them from there.


> for examples, I think it is on the example script (or preferentially **notebook**) to sort out the testing files it needs. I think the more overlap between example files and testing files the better, as this saves space, download capacity and also makes everything more reproducible as we are testing as close to the example workflow as possible. 

> If people find a need to consistently download all files in one shot I can add a function to just enumerate the bucket and fetch them all, but I think better to be lean to start with and see what our use cases turn out to be. 
 
 - [X] should the `testing` directory have an `__init__.py`?

> I would say no, as this brings some instantiated objects into global scope, which IMO you should have to request specifically. This is more a style thing but happy to change it if people think an easier import is warranted.

2023-04-17 14:29 UTC, kaminow approved these changes
looks great!

2023-04-17 15:07 UTC, apayne97 reviewed
Looks great, thanks!

2023-04-17 17:17 UTC, apayne97 approved these changes

2023-04-18 06:35 UTC, JenkeScheen approved these changes

2023-04-18 06:37 UTC, merged