Add early stopping based on loss convergence
choderalab/asapdiscovery pull request #245
Opened 2023-04-26 20:40 UTC by kaminow

The current `EarlyStopping` class works by checking if training is able to improve over the best loss seen, but sometimes this causes training to stop too early when the loss is still varying a lot but there happens to be one epoch with lower loss.

2023-05-11 00:57 UTC, hmacdope requested changes
Few small suggestions, but looking good.

2023-05-11 00:57 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/es.py
> +        self.losses += [loss]
Probably need some type checking on `loss` to make sure not appending junk.

2023-05-11 00:57 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
> +                raise ValueError("Option to --es_patience must be > 0.")
```suggestion
                raise ValueError("Option to --es_patience must be > 0 if  `best` es_type is used")
```

2023-05-11 00:57 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
> +                raise ValueError("Option to --es_n_check must be > 0.")
```suggestion
                raise ValueError("Option to --es_n_check must be > 0 if `converged` es_type is used.")
```

2023-05-11 00:57 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
> +                raise ValueError("Option to --es_divergence must be > 0.")
```suggestion
                raise ValueError("Option to --es_divergence must be > 0 if `converged` es_type is used.")
```

2023-05-11 00:57 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/scripts/train.py
> +                raise ValueError("Option to --es_divergence must be > 0.")
```suggestion
                raise ValueError("Option to --es_divergence must be > 0 if `converged` es_type is used.")
```

2023-05-11 00:57 UTC, hmacdope requested changes
Few small suggestions, but looking good.

2023-05-11 00:57 UTC, hmacdope requested changes
Few small suggestions, but looking good.

2023-05-11 00:57 UTC, hmacdope requested changes
Few small suggestions, but looking good.

2023-05-11 00:58 UTC, hmacdope commented
@kaminow apologies for the multiple review, idk exactly how that happened.

2023-05-11 14:42 UTC, kaminow commented
haha all good, should be ready for another look now!

2023-05-12 20:47 UTC, hmacdope approved these changes
Looks great @kaminow!

2023-05-12 22:49 UTC, merged