Add in ML by Target and redo ML classes to be schema
choderalab/asapdiscovery pull request #428
Opened 2023-08-10 12:23 UTC by hmacdope

Fixes #425

2023-08-11 01:16 UTC, hmacdope commented
@jthorton @kaminow Could I grab a review here? 

This is a big re-work of the way models are spec'd pulled and can be grabbed in a workflow all done with lots of schema.
 
1. The YAML file now has a schema `MLModelRegistry` made of subschema `MLModelSpec` which you can dynamically pull models from by date and target. 
2. Some changes to the YAML files themselves
3. The new Mac1 model is ready deployed and will be auto selected in the e2e WF
4. The models have a schema for when they are pulled down `LocalMLModelSpec`, making them easy to instantiate from local files
5. The inference classes themselves are schema. I still need to work out how to serialize the `mtenn` pytorch models or possibly even drop them and then reconstruct but I think I want to push this to a seperate PR.

2023-08-14 19:59 UTC, kaminow requested changes
love these new features! this will definitely help keep things more organized. I had a couple questions/thoughts, but I think the main one is regarding the necessity of having both the `MLModelSpec` and `LocalMLModelSpec` schema

2023-08-14 19:59 UTC, kaminow commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +class LocalMLModelSpec(MLModelBase):
actually, on second thought, I'm not sure I see a reason to have both `MLModelSpec` and `LocalMLModelSpec`. I think we could probably unify them into one, with a validator to make sure that there are either URLs+hashes, or local paths. in this case, `pull()` would populate the local path fields (and potentially load the weights/config into fields as well). it's also possible I'm just missing something though and both of these are useful to have separately.

2023-08-14 20:06 UTC, kaminow commented
> The inference classes themselves are schema. I still need to work out how to serialize the mtenn pytorch models or possibly even drop them and then reconstruct but I think I want to push this to a seperate PR.

regarding this, as long as the config used to construct the model is tracked along with the model weights, it should be trivial to reconstruct the `mtenn` models

2023-08-15 03:55 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +_SPECIAL_BUILD_MODEL_KWARGS = {MLModelType.schnet: {"pred_r": "pIC50"}}
Ok that makes sense, let me check how big a change this is.

2023-08-15 03:56 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +            models[model] = MLModelSpec(
I'll add 

```
Config:
   validate_assignment = True

```

which forces pydantic to do it.

2023-08-15 03:56 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +class LocalMLModelSpec(MLModelBase):
This makes sense, might reduce some complexity, ill investigate.

2023-08-16 00:58 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +_SPECIAL_BUILD_MODEL_KWARGS = {MLModelType.schnet: {"pred_r": "pIC50"}}
Ok fixed, great suggestion.

2023-08-16 02:39 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +class LocalMLModelSpec(MLModelBase):
I think I might leave this the way it is for a few reasons.

1. Making MLModelSpec dual purpose means you will need to check all the time if a model has been pulled and what the status of the fields are. If MLModelSpec is able to hold the local or remote spec basically every field becomes optional. 

2. LocalMLModel spec can be used to easily instantiate an inference class from some local weights lying around without having to specify all the other URL stuff say for local inference, testing and training if needed. 

3. There is a clearer mapping to the YAML file, MLModelSpec is the direct schema for the file.

2023-08-16 02:39 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/models/ml_models.py
> +class LocalMLModelSpec(MLModelBase):
We can discuss further at our meeting tommorow and also we can of course change in the future. :)

2023-08-16 22:24 UTC, kaminow approved these changes
looks great!

2023-08-16 22:24 UTC, merged