Script to separate the ligands added to scripts within asapdiscovery-data.
choderalab/asapdiscovery pull request #825
Opened 2024-02-06 02:33 UTC by SiyangPeng

## Description
Provide a brief description of the PR's purpose here.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [ ] Point 1 ...

## Questions
- [ ] Question 1 ..

## Status
- [ ] Ready to go

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-02-06 03:08 UTC, hmacdope requested changes
Looking great @SiyangPeng, just a few nitpicks. 

The other thing is could you add an endpoint in `asapdiscovery-data`'s `pyproject.toml? 

That way you can call it on the command line without needing `python` and it is added to environment on install. See here: https://github.com/choderalab/asapdiscovery/blob/main/asapdiscovery-data/pyproject.toml#L29

2024-02-06 03:08 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +    output_path = Path(directory + "output/")
You can just do 

```suggestion
    output_path = Path(directory) / "output"
    output_path.mkdir()
```
and then you can get rid of the `os.mkdir` on L48

2024-02-06 03:08 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +    def save_ligand_residues(structure_name, output_file):
Would you be able to un-nest these nested functions? Its no big deal but un-nested is the norm.

2024-02-06 03:08 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +    def save_subset_with_conect(structure_name, atom_ids, output_file):
Same here for nested functions

2024-02-06 03:08 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +        os.remove(lig_pdb_file)
you can use `tempfile` if you want but no stress either way.

2024-02-06 03:08 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +    save_openeye_sdfs(ligs, output_path / "Combined_ligs.sdf")
```suggestion
    save_openeye_sdfs(ligs, output_path / "combined_ligs.sdf")
```

2024-02-06 03:08 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +    save_ligand_residues("complex", local_path / "ligand_only.pdb")
Can you make `structure_name` (here "complex") into an arg (something like `args.c`) for more flexibility?

2024-02-06 16:58 UTC, apayne97 commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +Script to convert a single pdb file with multiple ligands all named LIG in
what about 
`split_fragment_screen.py`
`process_fragment_screen_output.py`
`split_single_pdb_into_many_sdf_files.py`
`generate_single_ligand_complex_from_fragment_screen.py`

2024-02-06 21:40 UTC, hmacdope commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +Script to convert a single pdb file with multiple ligands all named LIG in
Happy with any of those.

2024-02-06 22:16 UTC, SiyangPeng commented on asapdiscovery-data/asapdiscovery/data/scripts/separate_ligand_script.py
> +Script to convert a single pdb file with multiple ligands all named LIG in
Great, will do.

2024-02-07 04:34 UTC, hmacdope approved these changes
LGTM @SiyangPeng! @apayne97 you happy with this?

2024-02-07 04:36 UTC, hmacdope requested changes
Whoops blocking for conflicts

2024-02-07 04:36 UTC, hmacdope commented
@SiyangPeng, you will need to fix conflicts by merging with `upstream/main`, it may be easier to revert your (inconsequential) changes to the notebooks. Try running the following:

```
git fetch upstream
git merge upstream/main
... # make sure you fix conflicts
git commit
``

2024-02-07 19:56 UTC, hmacdope approved these changes
LGTM @SiyangPeng, thanks for this and congrats on your first contribution.

2024-02-07 20:52 UTC, merged