Fix simulation testcoverage and make some tests faster
choderalab/asapdiscovery pull request #837
Opened 2024-02-07 23:46 UTC by hmacdope

## Description
Provide a brief description of the PR's purpose here.
Fixes #836 
FIxes #776 

## Developers certificate of origin
- [X] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-02-08 02:49 UTC, hmacdope commented
Docking CI down from 1hr to 20 mins! hooray.

2024-02-08 02:52 UTC, hmacdope commented
@jthorton @ijpulidos @chrisiacovella could I grab a review here?

2024-02-08 17:16 UTC, chrisiacovella requested changes
you're missing "import os" in test_simulation statement.

2024-02-08 17:16 UTC, chrisiacovella commented on asapdiscovery-simulation/asapdiscovery/simulation/tests/test_simulate.py
You need to import os here

2024-02-08 23:35 UTC, hmacdope commented on asapdiscovery-simulation/asapdiscovery/simulation/tests/test_simulate.py
Ah thanks!

2024-02-08 23:37 UTC, hmacdope commented
@chrisiacovella should be fixed now :)

2024-02-09 11:38 UTC, jthorton commented
Great work @hmacdope glad to see the testing speeds improved. It looks like we can get a big coverage boost by testing the rmsd restraint code in simulate I have no idea how often we use that but it seems important. Can you have a go at adding some tests for it? Feel free to make it another PR if the testing is more complicated.

2024-02-12 00:00 UTC, hmacdope commented
@jthorton I have added tests for the RMSD code, and fixed a bug along the way (this is why we test ), would you mind reviewing?

2024-02-13 09:49 UTC, jthorton approved these changes
LGTM!

2024-02-14 01:09 UTC, hmacdope commented
I am going to assume that was a runner issue.

2024-02-15 01:25 UTC, merged