ASAP-Alchemy: Postera uploading
choderalab/asapdiscovery pull request #885
Opened 2024-02-27 10:46 UTC by jthorton

## Description
This PR extends the `asap-alchemy predict` CLI to optionally upload predictions to postera manifold. 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [ ] add uploading to predict
- [ ] track the biological target name on alchemy schema
- [ ] add tests to ensure column names are correct 

## Questions
- [ ] should we also be tracking the postera mol set name all the way from prep?

## Status
- [ ] Ready to go

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

2024-02-27 23:22 UTC, hmacdope commented on asapdiscovery-alchemy/asapdiscovery/alchemy/cli/utils.py
> +    return made_new_molset
This doesn't have to return if you don't use the rval.

2024-02-27 23:26 UTC, hmacdope requested changes
One nitpick, but other than that looks good! Test it live to make sure all the columns you want are there and then should be good to roll.

2024-02-27 23:26 UTC, hmacdope commented on asapdiscovery-alchemy/asapdiscovery/alchemy/cli/alchemy.py
> +    if bio_target is not None and postera_molset_name is not None:
Warn or log if one if `postera_molset_name` is present without `target`, ie someone probably wanted to upload but forgot to provide target. Currently doesn't give enough info about why no upload if skipped

2024-02-29 14:18 UTC, jthorton commented
okay tested locally and it seems to be working!

2024-02-29 18:10 UTC, hmacdope approved these changes
Legendary

2024-02-29 19:05 UTC, merged