Rework Trainer building in ML CLI
choderalab/asapdiscovery pull request #933
Opened 2024-03-29 19:41 UTC by kaminow

There were a couple of things that didn't work the way I wanted them to in the ML CLI that are fixed in this PR:
* Passing a `Trainer` config file ignore all other CLI args -> args from  config file are loaded, and then any CLI args that are specified override those in the file
* Continuing an existing run didn't do anything -> now works as expected

2024-04-04 02:36 UTC, hmacdope requested changes
Just make some utility functions to avoid some repetition, other than that looks good.

2024-04-04 02:36 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/cli.py
> +        trainer_kwargs = config_trainer_kwargs
This has been repeated a lot, you can just make it a function that lives in this module so you only have to update one spot

2024-04-04 02:36 UTC, hmacdope commented on asapdiscovery-ml/asapdiscovery/ml/cli.py
> +        trainer_config_cache.write_text(t.json())
Same here, just mash into a function that handles this (if possible)

2024-04-04 16:23 UTC, kaminow commented
@hmacdope good call, should be good to go now

2024-04-04 22:09 UTC, hmacdope approved these changes
LGTM, thanks for making the change.

2024-04-04 22:09 UTC, hmacdope commented
Ah @kaminow will need to fix conflicts

2024-04-05 00:46 UTC, kaminow commented
oop yeah I will fix

2024-04-05 20:08 UTC, merged